server:
  port: 8082

spring:
  datasource:
      url: jdbc:mysql://192.168.19.7:3306/cbei_v2_test_purchase?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: cibeimysql
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  application:
    name: springboot_prometheus



management:
    security:
      enabled: false
    metrics:
      export:
            prometheus:
                enabled: true
                step: 1m
                descriptions: true
    web:
        server:
            auto-time-requests: true
    endpoints:
        prometheus:
            id: springmetrics
        web:
            exposure:
                include: '*'
